#!/bin/bash

echo "Delete S3 bucket..."

# check if at least one argument is passed
if [ -z "$1" ]; then
  echo "Usage: $0 <bucket-name> [region]"
  exit 1
fi

BUCKET_NAME="$1"
aws s3api delete-bucket --bucket "$BUCKET_NAME" \
--query Location \
--output text

