#!/bin/bash

echo "List S3 bucket..."

# check if at least one argument is passed
if [ -z "$1" ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi

BUCKET_NAME="$1"
aws s3api list-objects-v2 --bucket "$BUCKET_NAME"

